### ISSUE TITLE
Gather feedback on Child Rmd approach

### ISSUE THREAD

**Issue by brunj7** [NCEAS/training-git-intro#2]
In this version I tested child Rmd files as a way to modularize the content.

Check with others about their thoughts on that

**Comment by jeanetteclark** [comment]
not as stoked on this idea - I have it implemented elsewhere and find it more confusing than anything. We should discuss more though

**Comment by brunj7** [comment]
Agreed. That was a little bit my conclusion. The final doc is very much of an empty shell and it is hard to track down what is going on in the submodules.

This being said, we might want to think about how similar nesting could be used for specific sections that might need updates, like installing software where versions can change. That could allow us to update past training material when a new version comes out if all the training were pointing to the same section.

**Comment by jeanetteclark** [comment]
Interesting, I feel like the case you just outlined above should just be handed with a regular update to the code.

The empty shell of the final chapter is what drives me the craziest. It ends up being a nearly empty but usually has some headers and a little bit of text, so some material is edited in there, some in the child markdowns, and it makes it harder to edit and overview an entire lesson without knitting.
